version: '3'
services:
  de-pyspark-jupyter:
    image: easewithdata/pyspark-jupyter-lab-old
    container_name: de-pyspark-jupyter
    hostname: de-pyspark-jupyter
    ports:
      - 8888:8888
      - 4040:4040
    environment:
      JUPYTER_PORT: 8888
      SPARK_UI_PORT: 4040
      SPARK_LOCAL_HOSTNAME: de-pyspark-jupyter
    networks:
      spark_network:
        ipv4_address: 172.25.0.3
    volumes:
      - spark_data:/data:rw

  de-spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: de-spark-master
    hostname: de-spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      spark_network:
        ipv4_address: 172.25.0.2
    volumes:
      - spark_data:/data:rw

  de-spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: de-spark-worker-1
    hostname: de-spark-worker-1
    depends_on:
      - de-spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://de-spark-master:7077"
    networks:
      spark_network:
        ipv4_address: 172.25.0.4
    volumes:
      - spark_data:/data:rw

  de-spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: de-spark-worker-2
    hostname: de-spark-worker-2
    depends_on:
      - de-spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://de-spark-master:7077"
    networks:
      spark_network:
        ipv4_address: 172.25.0.5
    volumes:
      - spark_data:/data:rw

  de-spark-history-server:
    image: bde2020/spark-history-server:3.3.0-hadoop3.3
    container_name: de-spark-history-server
    hostname: de-spark-history-server
    depends_on:
      - de-spark-master
    ports:
      - "18081:18081"
    networks:
      spark_network:
        ipv4_address: 172.25.0.6
    volumes:
      - /tmp/spark-events-local:/tmp/spark-events

networks:
  spark_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  spark_data:
